export const permissions = [
    "WATCH_PURCHASES_HISTORY",
    "WATCH_USER_QUESTIONS",
    "REPLY_USER_QUESTIONS",
    "MODIFY_BUYING_METHODS",
    "MODIFY_DISCOUNT",
    "MANAGE_INVENTORY",
    "CLOSE_STORE"
]
